### ISSUE TITLE
Attachment Files with the Same Name are Overwritten

### ISSUE THREAD

**Issue by LinnZawWin** [vgrade/XrmToolBoxAttachmentDownloader#2]
If the attachment files are not unique, the files are being overwritten. In the example below, there are 5 attachment files but only 4 of them can be found in the download folder since one of the files was overwritten.

![image](https://user-images.githubusercontent.com/14156926/120060769-b8f6f680-c0ad-11eb-8d18-495594fae906.png)

**Comment by vgrade** [comment]
This bug was fixed
