### ISSUE TITLE
Unclear in documentation - questions

### ISSUE THREAD

**Issue by gallina30** [vgrade/XrmToolBoxAttachmentDownloader#4]
When the tool downloads attachments from an entity, are the attachments still on the entity in the CRM? I'm looking for a tool to remove all email attachments from our environment. There are paid tools, but I'd like to use a free one as the organization doesn't have the budget for paid tools. 
Does this tool only download attachments from notes? Does it download attachments from emails?

**Comment by vgrade** [comment]
Hey @gallina30  This tool doesn't download email's attachment but notes attachment only and doesn't delete attachments from notes. You need to develop your custom utility to achieve your goal. You  can talk to me if need more help on what/how to write that utility. Thankyou

**Comment by vgrade** [comment]
@gallina30  I have updated the code here on github to downlead email's attachment if you provide email (or any activity tale) fetchxml. Update in xrmtoolbox will take some time but you can build this project in your machine and follow these steps to update the dll in your xrmtoolbox dlls to use the new feature.

**Comment by gallina30** [comment]
Wow thank you so much!!

**Comment by gallina30** [comment]
Another question - when the attachments are downloaded, is it like a copy is downloaded, or is it like the file is downloaded and no longer taking up storage in the environment?

**Comment by vgrade** [comment]
Copy, It's just downloader, doesn't delete anything in environment.

**Comment by gallina30** [comment]
thank you!!

**Comment by vgrade** [comment]
@gallina30 New version 1.0.9 of this tool now have feature of downloading email/activity attachment.  Tool now able to download attachment related to activity table like email. By default it downloads attachment record for activity type tables and notes table attachments for rest tables
